weit_clientes_homepage:
    path:     /hello/{name}
    defaults: { _controller: WEITClientesBundle:Default:index }

weit_clientes_index:
    path:    /index
    defaults:  {_controller: WEITClientesBundle:Clientes:index}

weit_clientes_agregar:
    path:    /agregar
    defaults:  {_controller: WEITClientesBundle:Clientes:agregar}

weit_clientes_ver:
    path:    /ver/{id}
    defaults:  {_controller: WEITClientesBundle:Clientes:ver}

weit_clientes_editar:
    path:    /editar/{id}
    defaults:  {_controller: WEITClientesBundle:Clientes:editar}

weit_clientes_update:
    path:    /update/{id}
    defaults:  {_controller: WEITClientesBundle:Clientes:update}

weit_clientes_crear:
    path:    /crear
    defaults:  {_controller: WEITClientesBundle:Clientes:crear}
    methods: POST

weit_clientes_delete:
    path:    /delete/{id}
    defaults:  {_controller: WEITClientesBundle:Clientes:delete}
    methods: [POST, DELETE]