<?php

namespace WEIT\EspectacularesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspectacularesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspectacularesRepository extends EntityRepository
{
}
