<?php

namespace WEIT\EspectacularesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VentasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentasRepository extends EntityRepository
{
}
